### ISSUE TITLE
This is not a issue but a suggestion to use   using namespace std;   instead of using std:: every time before cout in C++.

### ISSUE THREAD

**Issue by vishantrathi** [rutura/The-C-20-Masterclass-Source-Code#30]
https://www.programiz.com/cpp-programming/std-namespace 

Checkout above link for more explanation

 I do not want to misinform others, so please correct me if I'm wrong.

**Comment by vishantrathi** [comment]
https://www.programiz.com/cpp-programming/std-namespace

Checkout above link for more explanation

I do not want to misinform others, so please correct me if I'm wrong.

**Comment by Golem2024** [comment]
I do think you have a point but I think the creators should keep it as is, because this is a course aimed at beginners. It's difficult to figure out what works better for beginners, but since the content has already been created, and because a beginner wouldn't know what they're missing out on, it'd be difficult to prove that updating that would be ultimately be better.

Your point is that it's less keystrokes, but what about the learning aspect? How does updating improve learning or how does keep it impede learning?

**Comment by rutura** [comment]
Explicitly using std:: in front of names makes it clear where the name is coming from. Without that, the global namespace gets polluted pretty fast. Here is a good piece of [reading](https://stackoverflow.com/questions/1452721/whats-the-problem-with-using-namespace-std) on the subject.
